### PR TITLE
Add Wikipedia scraping example

### PR DESCRIPTION
**Pull request by ppinchuk**
Add example of end-to-end pipeline to scrape information about NREL's current director from Wikipedia articles.

@grantbuster Tracking a few things we have to resolve:

- [ ] Should we reduce the example to just a single `.py` or a `.ipynb` file?
- [ ] Should we add an end-to-end pipeline execution as an integration test?

### CODE REVIEW

**Comment by grantbuster** [comment]
> Add example of end-to-end pipeline to scrape information about NREL's current director from Wikipedia articles.
> 
> @grantbuster Tracking a few things we have to resolve:
> 
> * [ ]  Should we reduce the example to just a single `.py` or a `.ipynb` file?
> * [ ]  Should we add an end-to-end pipeline execution as an integration test?

I am indifferent to .py or .ipynb but definintely think we should just stick to one example file haha 

I am open to discussion on the integration test. Are we really talking about Azure API keys to github secrets and having real tests (not mocked)? I'm starting to lean this way as this repo gets more complicated and people keep modifying functionality for different applications.

**Comment by ppinchuk** [comment]
The current `.py` and `.ipynb` do serve slightly different purposes: The `.ipynb` goes slower and explains the steps, while the `.py` consolidates the code into a few functions. The `.ipynb` file actually loads the `.py` file at the end to show the full example. 

But, if we do scrap one, I'd prefer to ditch the `.py` file, since the notebook can serve as a guided tutorial.

**Comment by ppinchuk** [comment]
> I am open to discussion on the integration test. Are we really talking about Azure API keys to github secrets and having real tests (not mocked)? I'm starting to lean this way as this repo gets more complicated and people keep modifying functionality for different applications.

I think an integration test with real Azure API keys can get messy quickly - no one will want to debug it once something breaks outside of the ELM code (i.e. the key expires). But, if it's something that you want, I can implement it (either in this PR or a separate one).

I do agree that things can get complicated as people keep modifying the repo for their use-case. I'm not sure that adding the Azure keys would help with this problem though. I think this might be more of a question of the structure of the repo itself. Maybe we should have a discussion about exactly what problem you are trying to address?

**Comment by grantbuster** [comment]
> > I am open to discussion on the integration test. Are we really talking about Azure API keys to github secrets and having real tests (not mocked)? I'm starting to lean this way as this repo gets more complicated and people keep modifying functionality for different applications.
> 
> I think an integration test with real Azure API keys can get messy quickly - no one will want to debug it once something breaks outside of the ELM code (i.e. the key expires). But, if it's something that you want, I can implement it (either in this PR or a separate one).
> 
> I do agree that things can get complicated as people keep modifying the repo for their use-case. I'm not sure that adding the Azure keys would help with this problem though. I think this might be more of a question of the structure of the repo itself. Maybe we should have a discussion about exactly what problem you are trying to address?

UGH i'm sorry i'm so delayed on this. Let's have a quick call. Really i just want to make sure we know if things are runnable in a basic state... Maybe we could have tests that are meant to be run locally and are skipped if the respective env vars are not found? I'll reach out to chat more.

**Pull request merged**
